template = "https://github.com/giellalt/template-lang-und"
rev_id = 280
template_sha = "6beee360d8349c39749ac477719ead241493924c"

[replacements]
__GLOTTOLOG_ID__ = "mund1330"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-myu"
__UND2C__ = "myu"
__UNDEFINED__ = "Munduruk√∫"
__UND__ = "myu"
